name: CI

env:
  S3_BUCKET_NAME: "lerkasan.de-wwwroot"
  AWS_REGION:     "us-east-1"

on:
  push:
      branches: [ master ]
      paths-ignore:
        - 'infra/**'
        - '.github/**'
# for debugging purposes only
  workflow_dispatch:

jobs:

  build:
      name: Build via Gatsby
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [12.x, 14.x]

      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node-version }}

        - run: npm ci
        
#        - name: Configure a connection to Contentful CMS
#          run: npm run setup
#          env:
#            CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
#            CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}

        - run: npm run build --if-present
        - run: npm test

        - name: Build Gatsby content
          uses: jzweifel/gatsby-cli-github-action@master
          with:
            gatsby-arg: build

        - name: Archive an artifact
          uses: actions/upload-artifact@v2
          with:
            name: public-folder
            path: public

  infra:
      needs: build
      name: AWS S3 + Cloudfront infrastructure provisioning
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Provision infra via Pulumi
          uses: pulumi/actions@v1
          with:
            command: up
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
            AWS_REGION: ${{ env.AWS_REGION }}

  deploy:
      needs: [build, infra]
      name: Deployment to AWS
      runs-on: ubuntu-latest

      steps:
        - name: Download an artifact
          uses: actions/download-artifact@v2
          with:
            name: my-artifact

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.AWS_REGION }}

        - name: Upload static website content to an AWS S3 bucket
          run: |
            aws s3 rm s3://${{ env.S3_BUCKET_NAME }}
            aws s3 sync public s3://${{ env.S3_BUCKET_NAME }}/
